In [7]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils

### 데이터 준비하기
 - https://tykimos.github.com/Keras/warehouse/2017-3-8_CNN_Getting_Started_handwriting_shape.zip

### 데이터셋 생성하기

In [2]:
train_dataget = ImageDataGenerator(rescale=1./255)
train_generator = train_dataget.flow_from_directory(
    'data/handwriting_shape/train',
    target_size = (24, 24),
    batch_size = 3,
    class_mode = 'categorical')

test_dataget = ImageDataGenerator(rescale=1./255)
test_generator = test_dataget.flow_from_directory(
    'data/handwriting_shape/test',
    target_size = (24, 24),
    batch_size = 3,
    class_mode = 'categorical'
)

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


### 모델 구성하기
ImportError: Could not import PIL.Image. The use of `array_to_img` requires PIL  
이와 같은 에러 발생 시, 아래와 같이 조치함  
conda remove pillow  
pip install pillow  

In [3]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3,3),
                activation='relu',
                input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 22, 22, 32)        896       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 20, 20, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               819328    
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 387       
Total params: 839,107
Trainable params: 839,107
Non-trainable params: 0
_________________________________________________________________


### 모델 학습과정 설정하기

In [4]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### 모델 학습시키기

In [5]:
model.fit_generator(
    train_generator,
    steps_per_epoch=15,
    epochs=50,
    validation_data=test_generator,
    validation_steps=5
)

Epoch 1/50
15/15 [==============================] - 6s 394ms/step - loss: 0.8980 - acc: 0.6667 - val_loss: 0.4922 - val_acc: 0.6667
Epoch 2/50
15/15 [==============================] - 0s 6ms/step - loss: 0.2583 - acc: 0.8889 - val_loss: 0.1503 - val_acc: 1.0000
Epoch 3/50
15/15 [==============================] - 0s 6ms/step - loss: 0.0946 - acc: 0.9556 - val_loss: 0.0715 - val_acc: 1.0000
Epoch 4/50
15/15 [==============================] - 0s 6ms/step - loss: 0.0150 - acc: 1.0000 - val_loss: 0.0576 - val_acc: 1.0000
Epoch 5/50
15/15 [==============================] - 0s 6ms/step - loss: 0.0027 - acc: 1.0000 - val_loss: 0.0692 - val_acc: 1.0000
Epoch 6/50
15/15 [==============================] - 0s 6ms/step - loss: 0.0012 - acc: 1.0000 - val_loss: 0.0692 - val_acc: 0.9333
Epoch 7/50
15/15 [==============================] - 0s 6ms/step - loss: 6.1764e-04 - acc: 1.0000 - val_loss: 0.0500 - val_acc: 1.0000
Epoch 8/50
15/15 [==============================] - 0s 6ms/step - loss: 4.3710e-04 -

### 모델 사용하기

In [8]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.000 1.000 0.000]
 [0.000 0.003 0.997]
 [0.000 0.000 1.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [0.295 0.636 0.069]
 [0.000 0.090 0.910]
 [0.000 0.000 1.000]
 [0.000 1.000 0.000]
 [0.000 1.000 0.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]]
